# Generated by Django 2.1.7 on 2019-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
